name: noah
favicon: null
layout_spectrum: 0.17473
typography_spectrum: 0.74382
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101a11'
    - '#5885b4'
    - '#fefefc'
    - '#e2c7c4'
    - '#2e4160'
  brandStrength: 0.21547362324781716
  lightness: 0.4018339349422604
  saturation: 0.8695243669208139
  rhythmicContrast: 0.0937044401653111
purpose: []
